version: '3.9'

services:
  api:
    build: ./backend
    command: npm run start:prod
    env_file:
      - ./env/api.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - api
  mobile:
    build: ./mobile
    ports:
      - "8100:8100"
    depends_on:
      - api
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: brethren
      POSTGRES_USER: brethren
      POSTGRES_PASSWORD: brethren
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
